/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as ContactsNewRouteImport } from './routes/contacts.new'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/set-password': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/set-password': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/set-password': typeof SetPasswordRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/set-password'
    | '/tasks'
    | '/team'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/opportunities/$opportunityId'
    | '/opportunities/new'
    | '/accounts/'
    | '/contacts/'
    | '/leads/'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/set-password'
    | '/tasks'
    | '/team'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/opportunities/$opportunityId'
    | '/opportunities/new'
    | '/accounts'
    | '/contacts'
    | '/leads'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/interactions'
    | '/login'
    | '/marketing'
    | '/set-password'
    | '/tasks'
    | '/team'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/opportunities/$opportunityId'
    | '/opportunities/new'
    | '/accounts/'
    | '/contacts/'
    | '/leads/'
    | '/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InteractionsRoute: typeof InteractionsRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  AccountsNewRoute: typeof AccountsNewRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsNewRoute: typeof ContactsNewRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InteractionsRoute: InteractionsRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  SetPasswordRoute: SetPasswordRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  AccountsNewRoute: AccountsNewRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsNewRoute: ContactsNewRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
