-- ============================================================
-- Migration 011: Demote WIX-sourced Accounts back to Leads
--
-- The original CSV import (005/006 migrations) bulk-loaded the Master
-- Database sheet into accounts/contacts without going through the Lead
-- pipeline at all. That sheet's "Lead Source" column shows most of those
-- rows (901 of 1057) came from raw WIX website form fills, never
-- actually verified/qualified — only 156 were real Apollo-sourced
-- prospecting research. Treating all of them as "Accounts" (implying a
-- known, real company relationship) overstated what we actually know.
--
-- This migration:
--   1. For every Account whose name matches the WIX-sourced list below,
--      creates one Lead per existing Contact under it (source =
--      'Wix Website Inquiry'), or one company-level Lead ('-'/'-') if
--      the Account has no Contact on file.
--   2. Re-points any Interaction that referenced that Account/Contact to
--      the new Lead, so logged call/email history isn't silently lost.
--   3. Deletes the migrated Contacts and Accounts (tasks/opportunities
--      under these accounts were confirmed to be zero at the time this
--      migration was written, so nothing else needs re-pointing).
--
-- Accounts sourced from Apollo (156) are left untouched, as are any
-- Accounts not present in the original Master Database sheet at all
-- (e.g. ones created since, like the 4 new Ottawa accounts from the
-- Lead Conversion detail work).
--
-- Run this in the Supabase SQL Editor. It is one transaction — if
-- anything fails partway, the whole thing rolls back automatically.
-- ============================================================

do $$
declare
  v_org_id uuid := '00000000-0000-0000-0000-000000000001';
  r record;
  v_lead_id uuid;
  v_contact_leads int := 0;
  v_company_leads int := 0;
  v_deleted_contacts int;
  v_deleted_accounts int;
begin
  create temporary table wix_names (name text) on commit drop;
  insert into wix_names (name) values
    ('-'),
    ('1st Choice Family Services'),
    ('1x Technologies'),
    ('24-7 Power'),
    ('365 Sushi'),
    ('405 Amusement'),
    ('420 5th Ave NYC'),
    ('7 dimensions Inc'),
    ('705 BRBR Inc.'),
    ('A Taste Of Umami'),
    ('A small Shop next to hospital'),
    ('A&A Trailer Intertrade'),
    ('A. Vincent ApS'),
    ('ABC noodle house & seafood'),
    ('ABS1 Ltd.'),
    ('ACKMAN-ZIFF'),
    ('AJmax Ventures ltd'),
    ('AMB Signing Group'),
    ('AMUSE Co,.LTD'),
    ('ANND Commercial Real Estate'),
    ('ARB Investments'),
    ('ARC'),
    ('ASC'),
    ('Abv.S.R.L'),
    ('Academy of Art Compass Group'),
    ('Ace One Group'),
    ('Achievement Cooperation Pty Ltd'),
    ('Acmet London College'),
    ('Action Palace Carom Room'),
    ('Aegisx'),
    ('Aerolingual'),
    ('Afinity'),
    ('Agora Hospitalities Co., Ltd.'),
    ('Ah Ma Lobak Rice'),
    ('Aimbridge Hospitality'),
    ('Airport Authority Hong Kong'),
    ('Ajinomoto'),
    ('Akari Lighting and Technology Corporation'),
    ('Akashic'),
    ('Akesis Holistic Health'),
    ('Akranci-nefsos'),
    ('Ala Senses'),
    ('Alberts Boluss AB'),
    ('Alchemist Hub'),
    ('Ali-Dafu(TCM) Development Ltd.'),
    ('Ally Logistic Property'),
    ('Almashrek Devlopment & Marketing'),
    ('Aloft Sacramento Airport Hotel'),
    ('Aloha Shack LLC'),
    ('Alpha'),
    ('Ameritech business enterprise llc'),
    ('Amores Inc'),
    ('An elementary school'),
    ('Anatoly Vedmed'),
    ('And Switch'),
    ('Ann Andelman'),
    ('Ansons Realty'),
    ('Anuvan'),
    ('Apogeebuild'),
    ('Arab Media Network'),
    ('Arcadia'),
    ('Arcxis'),
    ('Areas'),
    ('Arena arcade'),
    ('Arrowhead Regional Medical Center'),
    ('Artemis'),
    ('Asian aroma llc dba kai sushi'),
    ('Asset Living'),
    ('Assimilatus'),
    ('Associated Students of Delta College'),
    ('Astim Resources Sdn Bhd'),
    ('Asunited Alliance Marketing Group'),
    ('Atelier Miah'),
    ('Australian Vending Company'),
    ('Automaten GmbH'),
    ('Aviah Hospitality Inc'),
    ('Awesome Beginning'),
    ('Aydin mobilyab'),
    ('Azelia Law PLLC'),
    ('Azul Foods'),
    ('BAITONG'),
    ('BFI'),
    ('BRB Vending'),
    ('BV studio'),
    ('Bain & Company'),
    ('Balti Ép-szer'),
    ('Bank of america'),
    ('Bar 201'),
    ('Barakah LLc'),
    ('Bard College'),
    ('Bay 9 Industries'),
    ('Beagle Estates'),
    ('Behem Tekstil Halı Mobilya San. Tic. Ltd. Şti.'),
    ('Beijing Xiao Man Tech Co; Ltd'),
    ('Berl''s'),
    ('Big C Retail Corporation Public Company Limited'),
    ('Big Fin Poke'),
    ('BioVis'),
    ('Bitton'),
    ('Blacktree Capital Limited'),
    ('Blue Lake Casino'),
    ('Blue Skyline Consulting'),
    ('BobaBing'),
    ('Bobapop'),
    ('Bobba Tea'),
    ('BoleMurphy industries'),
    ('Boletus'),
    ('Bonita Enterprise Co., Ltd'),
    ('Bonita Industries'),
    ('Brandywine Creek Campground'),
    ('Bresbo Worldwide'),
    ('BridgeMoto'),
    ('Bridgewater Studio'),
    ('Bronco Billy''s Casino'),
    ('Bruin Bruskis'),
    ('Bruu Bros'),
    ('Bubble Bee'),
    ('Bubbles Wash N Go'),
    ('Bucephale'),
    ('Built dreams LLC'),
    ('Buta Ramen'),
    ('Byers Institute'),
    ('C&A Distributors vorp'),
    ('C&W Trading LLC'),
    ('C.P.A. PISCINE RO SRL'),
    ('CC''s vending services'),
    ('CCHAC'),
    ('CCSD'),
    ('CGI'),
    ('CREATIVE VENDING SOLUTIONS LLC'),
    ('CT Wellness Co.'),
    ('CTS Group'),
    ('CW logistics'),
    ('Caesars Entertainment'),
    ('California Asian Pacific Chamber of Commerce'),
    ('Campus Food Solutions'),
    ('Campus Markets - University of Georgia'),
    ('Canada Golden Groups'),
    ('Cane Health Inc.'),
    ('Canne.J'),
    ('Capsule'),
    ('Caravan Foods'),
    ('CashOut Pro'),
    ('Catersmart'),
    ('Caytor Consulting'),
    ('Cecina Colima'),
    ('Cedar Grove Farm LLC'),
    ('Cellares Corp'),
    ('Charles'),
    ('Chase N’ Flamez'),
    ('Cheek Brings ltd'),
    ('Cheerful Adventure Co.'),
    ('Chef Collin Browned'),
    ('Chestnut'),
    ('China Airlines'),
    ('China Resources Enterprise Property Investment Company Limited'),
    ('China University of Science and Technology'),
    ('Chucktown Boxed Eats'),
    ('Chupacabra tattoo'),
    ('Churriño / CGD WFFS LLC'),
    ('Château d''Urspelt SA'),
    ('Cimeo'),
    ('Cinunan'),
    ('Clarity Specialists LLC'),
    ('Classic Foods & Vending/Coca Cola Bottling Co. United'),
    ('Claudia Coimbra Nutricionista'),
    ('Clinical Reference Laboratory'),
    ('Cllix hotel and apartments'),
    ('Cocin arte accesorie s.l.'),
    ('Cohana LLC'),
    ('Community Club in CA'),
    ('Compass'),
    ('Compass Group/ Chartwells Higher EDU'),
    ('Compass North America'),
    ('Cornell University (late night ramen for engineering students), in Ithaca, NY - Skyview Mall, Flushing NY with high foot traffic - JFK airport, LGA airport, EWR airport'),
    ('Corporate Vending Solutions'),
    ('Crane Games'),
    ('CreatePossible LLC'),
    ('Creative Dining Services'),
    ('Cristel'),
    ('Crosscut Mountain Sports Center'),
    ('Crown Castle'),
    ('Crush Baseball Facility'),
    ('Css'),
    ('Cupid trading limited'),
    ('Currently in process of creating'),
    ('Custom Events Baltimore'),
    ('Cyber Cafe or ghost kitchen'),
    ('D&V'),
    ('DJH Group'),
    ('Daaiyunfood'),
    ('Dallas executive wellness'),
    ('Dang Good Food'),
    ('Dark Shot Coffee'),
    ('Delirama'),
    ('Delta'),
    ('Delta Mechanical'),
    ('Denver CBRE'),
    ('Devorer'),
    ('Diamond State Moto Complex LLC'),
    ('Doghouse Inc'),
    ('Don’t Have'),
    ('Doubletree San Francisco Airport- Burlingame'),
    ('Draft Theory'),
    ('Dream house loans'),
    ('Duggar dogs'),
    ('Duoma'),
    ('E'),
    ('E & G Estate Sales'),
    ('ENTAS'),
    ('EdCraft.io'),
    ('Eden Creations Consulting'),
    ('Educity Park Frisco LLC'),
    ('Edwards Lifesciences'),
    ('El Bardo Restaurants'),
    ('Elevensies Vending CO'),
    ('Elite Solution'),
    ('Emart holding s/b'),
    ('Enablon'),
    ('Enlumin'),
    ('Epicurean Group'),
    ('Espana industry Co.,Ltd'),
    ('Eternal Strong Sdn Bhd'),
    ('Etiwanda Res corp'),
    ('Europe Visa Plus（Hong Kong）Limited'),
    ('Eve consultation llc'),
    ('Executive Inn'),
    ('Express vendors'),
    ('FAH CLAUDE HOLDING SAS'),
    ('FEISHU'),
    ('FUDO'),
    ('Far niente'),
    ('Felix Advisory Group'),
    ('Feng Cha Teahouse Fullerton'),
    ('FernanTECH'),
    ('Field Holding Company'),
    ('Fieten Spatial Impact'),
    ('Fifty SixSeventy Seventy'),
    ('Firefly Express'),
    ('Fireside Flats Apartments'),
    ('First Sight Coffee & Bar'),
    ('Fishmaster'),
    ('Fitnotech'),
    ('Flavour Rich Pte Ltd'),
    ('FlipIt Gaming Cafe'),
    ('Flsunsine'),
    ('Flying fish international trade co.'),
    ('Food capital ptd'),
    ('Fooda'),
    ('FoodieTek'),
    ('Formosa Market inc'),
    ('Founder of Framex.AI and a ramen lover myself'),
    ('Freelance'),
    ('Freezer company'),
    ('Fresh eat'),
    ('Fujiyaroundrock'),
    ('Full Sail LLC'),
    ('Fun car auto'),
    ('FundsEvents'),
    ('Fusehealth'),
    ('Future Technologies LLC'),
    ('G2 anesthesia'),
    ('GET24'),
    ('Galindo express'),
    ('Ganellen Property'),
    ('Garza entertainment llc'),
    ('GastroSzene'),
    ('Gastroco / One Pint'),
    ('Gatsby(Shanghai) Business Management Co., Ltd.'),
    ('Geofence Global Co., Ltd.'),
    ('Get It Analytics'),
    ('Get it done services'),
    ('GhostPizza'),
    ('Gilley''s Park City'),
    ('Globrews (S) Pte Ltd. - Singapore'),
    ('Gold Water (HK) Pty Limited'),
    ('Golddoor Asset Management Inc'),
    ('Goldie&Adi'),
    ('Good Eating Company US YKE and Gilead FC Price Discussion'),
    ('Good Mom LLC'),
    ('Good2Grow'),
    ('Gradam Group LLC'),
    ('Graico International'),
    ('Great Harvest Bread Company'),
    ('Great White Products Pty Ltd'),
    ('Greater oaks'),
    ('Green Bee'),
    ('Green Fashion Company LLC'),
    ('Green Land Investment'),
    ('Green Machine'),
    ('Griffon Brewery & Gastropub'),
    ('Gs noods'),
    ('Guckenheimer ISS World'),
    ('H & W Studio LLC'),
    ('HERS'),
    ('Halbertech'),
    ('Hamlet Foods'),
    ('Happy YoYo LLC'),
    ('Haywards heath sushi ltd'),
    ('Hello Kity & Friends Town Hello Kitty Ramen Kitchen Corner Sanrio'),
    ('Helpfulway, Inc'),
    ('Helsingin Juhlateltta & Easinki Group Oy'),
    ('Heman LLC'),
    ('Heptobelisk Holdings, LLC'),
    ('Hermanos foods'),
    ('Hey Luv LLC'),
    ('Hi Wire Brewing Second call'),
    ('Hi-Wire Brewing'),
    ('Hibachi and sushi Alien'),
    ('High Beam Technologies'),
    ('Hirosa LLC'),
    ('Holding byhnh'),
    ('Holiday Inn express Singapore Clarke Quay'),
    ('Hollywood Casino'),
    ('Hollywood Casino Toledo'),
    ('Honda of Canada Manufacturing'),
    ('Hornbill Brewery Sdn Bhd'),
    ('Hot Spot'),
    ('Hotel De Anza'),
    ('Hotel and shopping centers Livify'),
    ('House of Tangram'),
    ('HoustonsGotSpice'),
    ('Huang Home Cooking GmbH'),
    ('Hulucat International Limited'),
    ('IANS LLC'),
    ('ICEO Technologies'),
    ('IGS Plus'),
    ('IUP Academy of culinary arts'),
    ('IVA'),
    ('Ibcv Iasi'),
    ('Idacs inc'),
    ('Imagine Airport Ventures'),
    ('Imc Companies'),
    ('Imperial Square Liquor'),
    ('Imperial designs'),
    ('Independent'),
    ('Independent Individual'),
    ('India Home inc'),
    ('Indie Trader'),
    ('Individual'),
    ('Individual Entrepreneur'),
    ('Indiviual'),
    ('Indvest USA'),
    ('InfoGalaxy Global Pty Ltd'),
    ('InnoVend LLC'),
    ('Innovators Direct Pty Ltd'),
    ('Insiteh'),
    ('International Dairy Deli Bakery Association'),
    ('Invesca Development Group'),
    ('Isekai Shokudō'),
    ('Ivy Rose Events'),
    ('Izushin Corporation'),
    ('J A DAVIS ENTERPRISE'),
    ('JAY Station LLC'),
    ('JC vending machines australia'),
    ('JCK TRADING LLC'),
    ('JCP Ventures LLC'),
    ('JDK LLC'),
    ('JETinc'),
    ('JIA Property Preservation LLC'),
    ('JLL'),
    ('JPAB'),
    ('JT LLC'),
    ('JTI Holdings Pte Ltd'),
    ('Jamaica Hospital'),
    ('James Lachlan Pty Ltd'),
    ('Jay Asharam V Inc'),
    ('Jemswin international development ltd'),
    ('Jessica Rudzewicz'),
    ('Jin Dal inc.'),
    ('Jiro Akpobome DDS PLLC'),
    ('Johnson & Wales University'),
    ('Joint Alliance Group, Inc'),
    ('Jones Lang LaSalle Real estate company'),
    ('Jotstep'),
    ('Juji Group Ltd.'),
    ('Jumpstart'),
    ('Just ramen around'),
    ('K&P Enterprises'),
    ('Kai noodz'),
    ('Kairoi Residential'),
    ('Kanjiru LLC'),
    ('Kanpai (Aus) pty ltd'),
    ('Kasey Services'),
    ('Kaushiki'),
    ('Kedavra tattoo supply'),
    ('Kelly’s Place inc'),
    ('Kenseido'),
    ('Kids Connection'),
    ('KimBap Station Corp/KingKong Ramen(DBA)'),
    ('Kinetik Tools'),
    ('King & Co. & King Lin Prop'),
    ('KingdomBuilding Leadership, Inc.'),
    ('Kipling consulting LLC'),
    ('Kokoshungsa'),
    ('Konen & Lorenzen Management & Real Estate Solutions'),
    ('Kuai'),
    ('Kustom Vending'),
    ('Kyocera International, Inc.'),
    ('L inter Corporation'),
    ('L&G'),
    ('L.T.N.I company'),
    ('LED ONE CORP'),
    ('LLIBRA ENTERPRISE'),
    ('LS Studio'),
    ('La Rose patisserie'),
    ('La loggia art b&b Inc.'),
    ('Laberta'),
    ('Lafayette Sweets'),
    ('Lantz properties'),
    ('Lao Wang Noodle Bar'),
    ('Larry Satkoski'),
    ('Las Vegas Andy referral'),
    ('Lasell University'),
    ('Lavo Pte Ltd'),
    ('Lazy Jays LLC'),
    ('Leap Asset Solutions'),
    ('Lee''s Gift LLC'),
    ('Legacy Eco'),
    ('Light house G LLC'),
    ('Linz ag froschberg'),
    ('Lip Smackers LLC & SpareTime Grill'),
    ('Live Casino Maryland'),
    ('Llc'),
    ('LocaliQ'),
    ('Lola'),
    ('Londis'),
    ('Long Point Realty Partners'),
    ('LoopMedia'),
    ('Lt group'),
    ('Luckee Kitchen'),
    ('M&A Group'),
    ('M&N Vend Vibe'),
    ('MAGO S.A.'),
    ('MC Matthew Enterprises Inc.'),
    ('MCF Consulting'),
    ('MCLG'),
    ('MJM Robot Foods Oy'),
    ('MaCuVerse LLC'),
    ('Macau'),
    ('Maes incorporated'),
    ('Magic Media, Co.'),
    ('Make Moves DFW'),
    ('Mama''s bakery+cafe'),
    ('MaraJai'),
    ('Marble Yakiniku'),
    ('Marcus Contemporary'),
    ('Marriott Vacation Club'),
    ('Matis Capital Ltf'),
    ('Matrix Aviation Inc.'),
    ('Maxari'),
    ('Maya Foods'),
    ('McDantim'),
    ('McKa Enterprises'),
    ('Meadows'),
    ('Meaningful Ventures'),
    ('Meats Mo PH'),
    ('Mediase7en'),
    ('Mee Sungai Lembing (M) Sdn Bhd'),
    ('Mel, Nat and Thai Corp'),
    ('Menalize'),
    ('Mesa exteriors'),
    ('Metaverse Entertainment Holdings INC'),
    ('Mex exhibitions'),
    ('Miami Culinary Institute'),
    ('Miami Red Dragons Inc'),
    ('Micron'),
    ('Midway Tavern & Casino'),
    ('Midwest Entertainment'),
    ('Mie ayam banyumas'),
    ('Mikhail Vinitsky'),
    ('Mile High City Labs, LLC DBA Verse Denver'),
    ('Military bases'),
    ('Mindco. Mental Health & Wellness Boutique'),
    ('Mint and Mango Co., LLC'),
    ('Modern Concepts LLC'),
    ('Mohave Farms'),
    ('Molloy University'),
    ('Mom and Me  Snacks'),
    ('Mom and me snacks'),
    ('Morris Park Dental'),
    ('Motycka enterprises'),
    ('Mountain Capital Investment Advisors, Inc.'),
    ('Mr & Mrs Cosac'),
    ('Mr Crab'),
    ('Mr. and Mrs. Cosac'),
    ('Mr.BBQ'),
    ('Mukai incorporated'),
    ('Murray Management LLC'),
    ('Mustang Club dba RoboBites'),
    ('My'),
    ('My Noodle House'),
    ('My noodles'),
    ('MyFastHeatFood'),
    ('MÖGETEE'),
    ('N/A'),
    ('N/A(currently)'),
    ('N38'),
    ('NA'),
    ('NEP Group'),
    ('Nachtraven'),
    ('Name is not registered yet. working on it.'),
    ('Nanbantei International (HK) Limited'),
    ('Nashville State Community College Foundation'),
    ('National Australia Bank'),
    ('Need to come up with one'),
    ('Negawatt Partners, LLC'),
    ('Nerdology Toys & Collectibles'),
    ('Net Tree Inc'),
    ('Neva BV'),
    ('New Bibek Enterprises Pvt Ltd'),
    ('New Business'),
    ('New Life Coffee LLC'),
    ('NextGenFoods LTD'),
    ('Ngohuarose Corporation'),
    ('Nike'),
    ('Nine Mars Inc'),
    ('No company'),
    ('No company yet'),
    ('No name yet'),
    ('No website, just a Facebook page "Wholesome Dine-or-Dash"'),
    ('Noah''s Ark Sanctuary'),
    ('Noddle Bot'),
    ('Noem''s random stuff'),
    ('Nolan projects'),
    ('Non'),
    ('Noname'),
    ('Noodlepig Ramen Shop'),
    ('North Freedom'),
    ('Northwest Indian College'),
    ('Nosh Simple'),
    ('Nourish Markets'),
    ('Nova Inov Group'),
    ('Novatre ehf'),
    ('Novo marketplace'),
    ('Novogen'),
    ('NutriAsia'),
    ('Nuvision Construction'),
    ('O'),
    ('OLG'),
    ('OTAKING B.V.'),
    ('Ogatas hot foods'),
    ('Olive Co.'),
    ('Oltra, LLC'),
    ('Onecent sdn bhd'),
    ('Orange Door Properties'),
    ('Orgcrafters'),
    ('Orientech LLC'),
    ('Osprey Financial Services'),
    ('PAMGO'),
    ('PCP'),
    ('PG Grup LLC'),
    ('POMELO-Tech UG'),
    ('PROSTHERA ENTERPRISE'),
    ('PT Hetanny Investment Partners'),
    ('PT. Mata Air Boga Lestari'),
    ('Pacific NW Lifestyle'),
    ('Palette Ventures'),
    ('Panda (Global) Group Co., Limited'),
    ('Park Cafe Gourmet Market'),
    ('PaulAxler'),
    ('Penn Medicine Princeton Medical Center'),
    ('Pennrose Management Company'),
    ('Perez Sales and Services, LLC'),
    ('Phantom Boba'),
    ('Pharmacy Greek'),
    ('Pharmalinc limited'),
    ('Philippine Vending Corporation'),
    ('Phillipo''s LLC'),
    ('Pine manor apartments'),
    ('Pinnacle SF'),
    ('Pit Stop'),
    ('Planck Technologies, LLC'),
    ('Plug Media'),
    ('Plur Cafe'),
    ('Poke Burri'),
    ('Pomelo'),
    ('PowerBuild construction'),
    ('Powerbuild'),
    ('Premier Box Vending inc'),
    ('Presidio motel'),
    ('Pressure Nashville'),
    ('Presto'),
    ('Private'),
    ('Private chef, finding new business ideas in cooking.'),
    ('Proactive Logistics USA'),
    ('Providence Mt. St. Vincent'),
    ('Prulink investment Pte ltd'),
    ('Punte'),
    ('Pure Juice Bar & Cafe'),
    ('Purer ltd'),
    ('PwC'),
    ('QFC'),
    ('QWK Media'),
    ('Qbservices'),
    ('Qingdao Towin Digital Technology Co.,Ltd.'),
    ('Queuecut Pte Ltd'),
    ('RESTAURACE U BÍLÉHO KONÍČKA'),
    ('RF Food Services'),
    ('RFK'),
    ('RPV Ventures'),
    ('RTP Production'),
    ('RaRa Ramen GmbH'),
    ('Rainy Day Cage'),
    ('Ramen -1'),
    ('Ramen Empire'),
    ('Ramen Rush LLC'),
    ('Ramen house'),
    ('Re-trace ; llc'),
    ('Reel Safe LTD'),
    ('Renovar'),
    ('Replay Classic Arcade'),
    ('Retired'),
    ('Rice University'),
    ('Rikki chan'),
    ('Rivers Casino Philadelphia'),
    ('Rivvid LLC'),
    ('Rob the handy-man'),
    ('RoboKitchen Inc'),
    ('Robothink'),
    ('Rochester Institute of Technology'),
    ('Roosevelt China Investments'),
    ('Rovaye Hospitality'),
    ('Royal Food Service'),
    ('Royal Ridge Fruit & Cold Storage, LLC'),
    ('Rubeni Corp.'),
    ('Ruby Liu Commercial Investment Corp/ Central Walks'),
    ('SANRITSU COMPANY LIMITED'),
    ('SEEDNUR General Trading LLC'),
    ('SENSO POD FOODSTUFF TRADING LLC'),
    ('SF Ramen Noodle'),
    ('SH group'),
    ('SMART BLOCKTECH CO LTD'),
    ('SMDG'),
    ('SN & Partners'),
    ('SSD Vending Solutions LLC'),
    ('STELLARLUNE'),
    ('STYLO'),
    ('Saffran Fàxafen'),
    ('Salted Roots'),
    ('Salumi'),
    ('San Bernardino Physicians Associates'),
    ('San Francisco Bay University'),
    ('San diego single operator'),
    ('Santa Rosa CA area can possibly do Sonoma Airport'),
    ('Sara Hotels'),
    ('Savisko'),
    ('SavvySnacks'),
    ('Scherado Enterprise'),
    ('Schomackers Home Galleries'),
    ('Sebastian Poraj'),
    ('SeeryLogic, LLC'),
    ('Sego on the go'),
    ('Self'),
    ('Self Employees'),
    ('Self employed'),
    ('Seoul LLC'),
    ('Serve'),
    ('ShanFranVending'),
    ('Shangri-La International Hotel Group'),
    ('Shark Miro packs pty ltd'),
    ('Sharp and Heavy, LLC'),
    ('Shax'),
    ('Shel&norman Ltd'),
    ('Sheppard Holdings LLC'),
    ('Shogun ichi'),
    ('Shopping center in San Antonio'),
    ('Shorter Enterprises LLC'),
    ('Silva Catering SRL'),
    ('Simon Property Group'),
    ('Simply By Design'),
    ('Skynetclouds'),
    ('Slaymation LLC'),
    ('Sneaker Foods'),
    ('Sng'),
    ('Sodexo'),
    ('Soon to be'),
    ('Sorfin Yoshimura Tokyo Co. Ltd.'),
    ('Soul Drive Global'),
    ('Spacestation CPG'),
    ('Sparknify'),
    ('Spica Realty'),
    ('Spring arts tower, inc'),
    ('Squirvi Vending'),
    ('Starlight MGL'),
    ('Starlight Minigolf second meeting carlos and marcus, mini golf phoenix'),
    ('Stars Casino'),
    ('Starside Drugs LLc'),
    ('Startup'),
    ('State Trading Organization Plc'),
    ('Stetson University'),
    ('SticksXSpoonsLLC'),
    ('Stir crazy kitchen'),
    ('Sumire Station'),
    ('Sunmoonstar'),
    ('Sunny and 75 Hospitality'),
    ('Sunny’s Nom Noms'),
    ('Super Hi Foods Ltd'),
    ('Sushipoint Ltd'),
    ('Sweet Seoul'),
    ('T F International Pty Ltd'),
    ('T&Z investment llc'),
    ('TBA'),
    ('TBD'),
    ('THE ONE- Florida International University'),
    ('TTT'),
    ('Tabletop Library Berkeley'),
    ('TamTam'),
    ('Tangynation LLC'),
    ('Taste Of Korea'),
    ('Tayibah Refesh'),
    ('Tazaki Foods Yutaka Sister company of mutual trading Partnership ramen'),
    ('Tea Time LLC'),
    ('Teazzi Tea Shop'),
    ('Techtronix'),
    ('Texas Instrument'),
    ('Tha Phunk Shop LLC'),
    ('The BDC Group'),
    ('The Claussen Group'),
    ('The Forrest Group cold storage solution'),
    ('The Glass House Cafe'),
    ('The Great Canadian Bagel'),
    ('The Joerin Group'),
    ('The Lab Holding'),
    ('The Mercy Group'),
    ('The Raxk SB'),
    ('The Red Marker Pte Ltd'),
    ('The Royal Line Construction LLC'),
    ('The Siu-Chang Group'),
    ('The Spot'),
    ('The Vault Gaming Center'),
    ('The Westin Tashee Resort, Taoyuan'),
    ('The wellness code'),
    ('TheCapybaraCompany'),
    ('TheOtakingAmsterdam'),
    ('TheromoPlus'),
    ('Think Asia / Hawker Bar'),
    ('Thoman Holding BV'),
    ('Three Rivers Casino'),
    ('Tms'),
    ('Transwestern'),
    ('Tres gatos'),
    ('Turn To Services'),
    ('UCI LLC'),
    ('UDK Amusements'),
    ('UK Hetai Trading Co. ltd / Asia Food products'),
    ('Ultimate grinds'),
    ('Uncommon Goods'),
    ('Unimarch'),
    ('United Home Teams, Inc.'),
    ('Unity Prosper'),
    ('University cooperative organization'),
    ('University of Nebraska'),
    ('University of North Carolina at Chapel Hill'),
    ('University of Notre Dame'),
    ('University of Oregon Portland'),
    ('University of Pennsylvania'),
    ('University of South Florida Aramark'),
    ('Unknown TCG SHOP'),
    ('Urban Teach'),
    ('Urbano trading'),
    ('Uwajimaya Inc'),
    ('VH'),
    ('VV Holding Inc.'),
    ('VZ Solutions LLC'),
    ('Valley Plaza Company'),
    ('Van Winckel Jelle GCV'),
    ('Varela Ventures'),
    ('Variety Solutions'),
    ('Vcho'),
    ('Vend Central'),
    ('Vended!'),
    ('VendingSpace'),
    ('Vendo-Land'),
    ('Venturebnb LLC'),
    ('Viet-nomz'),
    ('VietPride LLC'),
    ('Visa Comply'),
    ('Visionary Trio'),
    ('Vita Dubchak'),
    ('Vostochny Veter'),
    ('Vum cin enterprises incorporate'),
    ('W Pro Kitchen'),
    ('WGG Hospitality'),
    ('WHSmith North America'),
    ('WILLOW-ICS'),
    ('WY international inc'),
    ('WaffleBear'),
    ('Wake Forest University Dining HTCG'),
    ('Wang-Ke Anime Studios'),
    ('Washington University in Saint Louis'),
    ('Watchful Innovations'),
    ('Weitai Machinery Co,.Ltd.'),
    ('Wemega GmbH'),
    ('West Coast Asset'),
    ('West Kings International Investment Ltd.'),
    ('West River Financial'),
    ('Whiskyclub'),
    ('White market'),
    ('Wifi Gallery'),
    ('Wingmaker'),
    ('Winmate'),
    ('Wismettac Asian Foods: Supplier partner'),
    ('WoW enterprise'),
    ('Worldwide Convenient Solutions'),
    ('XK LLC'),
    ('Xavier University Compaas Group'),
    ('Xinjiangzhi china'),
    ('YOGIYO'),
    ('Yang jenq machinery'),
    ('Yatai ramen'),
    ('Yedim'),
    ('Yello Creative Services Inc'),
    ('Yet To Form'),
    ('Yet to set up a company'),
    ('Yo Kai express'),
    ('Young Industrie'),
    ('Yume and Kuma llc'),
    ('Yuvi'),
    ('ZENVIBE'),
    ('Zanox Group'),
    ('albertosaffioti@live.it'),
    ('andy referral, Las vegas NV, second call boba and ramen'),
    ('architect firm hired for a company called Land research in Fremont CA, want ramen machine they connected with andy first through CS email since no email response from cs email'),
    ('arcom'),
    ('cali bros investment LLC'),
    ('cfeconn1'),
    ('daruma sushi'),
    ('easy load trading'),
    ('ebe'),
    ('eggcellent'),
    ('ejaz kamboj MD INc'),
    ('eurlvitoalgeria@gmail.com'),
    ('fare iimpasto'),
    ('foundation housing co'),
    ('fuzhaoyuan.llc'),
    ('gplus'),
    ('holdings'),
    ('imart'),
    ('in progress'),
    ('jw greenland sdn bhd'),
    ('katy houston texas, robo cafe and AMA kitchen'),
    ('kirin oh llc'),
    ('kvi'),
    ('las vegas, nv, cat cafe boba machine'),
    ('lepastelcafe'),
    ('louisvuitton China'),
    ('magicalkeys - real estate'),
    ('michael zhu'),
    ('mrds distributers'),
    ('new China'),
    ('nextar'),
    ('none'),
    ('none at this time'),
    ('not UCB but former student now lives in Denver CO  interested in Ramen machine  kendra'),
    ('portland oregon interested in ramen first and  maybe boba have a micromarket startup'),
    ('ramen goons'),
    ('ramenria'),
    ('resilient Gems'),
    ('revitacore'),
    ('rodewayinn&suite'),
    ('sanuk Delicatessen Managment'),
    ('savings more digital marketing LLC'),
    ('savoxthailand'),
    ('saw our machine at TPE airport'),
    ('sc vending'),
    ('second call for st louis, most likely hospitals both machine type'),
    ('shanghai daogu co.ltd'),
    ('smartcuisine solutions'),
    ('tahan15 llc'),
    ('university'),
    ('west fork whiskey co.'),
    ('wylblueocean'),
    ('xnf tech co.,ltd'),
    ('アイビック食品'),
    ('コンパスグループ・ジャパン モルガンスタンレー店'),
    ('トライト株式会社'),
    ('一頭也燒肉'),
    ('享佇民宿'),
    ('仕盟貿易有限公司'),
    ('個人創業'),
    ('千葉餐飲股份有限公司'),
    ('台中市'),
    ('喬碩商行'),
    ('宜蘊生醫股份有限公司'),
    ('小島遇見他'),
    ('小憩片刻創新智能有限公司'),
    ('屁虎爱吃网络餐饮'),
    ('昌懋懿有限公司'),
    ('有限会社最上商店'),
    ('松崎商事株式会社'),
    ('株式会社ネクスト'),
    ('株式会社リッショーコーポレーション'),
    ('玄宇數位通訊'),
    ('簡築旅策股份有限公司'),
    ('統一超商股份有限公司-關廟商場'),
    ('臺北流行音樂中心'),
    ('航空服務（香港）有限公司'),
    ('華美航運股份有限公司'),
    ('高田食堂'),
    ('鹿鹿企業社')
  ;

  create temporary table wix_accounts on commit drop as
  select a.* from accounts a
  join wix_names w on lower(trim(a.name)) = lower(trim(w.name));

  create temporary table contact_lead_map (
    contact_id uuid,
    account_id uuid,
    lead_id uuid
  ) on commit drop;

  create temporary table account_fallback_lead (
    account_id uuid primary key,
    lead_id uuid
  ) on commit drop;

  -- One Lead per existing Contact under a WIX-sourced Account
  for r in
    select c.id as contact_id, c.first_name, c.last_name, c.email, c.phone, c.title,
           wa.id as account_id, wa.name as company_name, wa.domain, wa.region, wa.owner_id
    from contacts c
    join wix_accounts wa on wa.id = c.account_id
  loop
    insert into leads (
      organization_id, first_name, last_name, email, phone, title,
      company_name, company_domain, region, source, source_detail,
      lifecycle_stage, owner_id
    ) values (
      v_org_id, r.first_name, r.last_name, r.email, r.phone, r.title,
      r.company_name, r.domain, coalesce(r.region, 'US'), 'Wix Website Inquiry',
      'Migrated from WIX-sourced account', 'New', r.owner_id
    )
    returning id into v_lead_id;

    insert into contact_lead_map (contact_id, account_id, lead_id) values (r.contact_id, r.account_id, v_lead_id);

    insert into account_fallback_lead (account_id, lead_id)
    values (r.account_id, v_lead_id)
    on conflict (account_id) do nothing;

    v_contact_leads := v_contact_leads + 1;
  end loop;

  -- One company-level Lead for WIX-sourced Accounts with no Contact on file
  for r in
    select wa.id as account_id, wa.name as company_name, wa.domain, wa.region, wa.owner_id
    from wix_accounts wa
    where not exists (select 1 from contacts c where c.account_id = wa.id)
  loop
    insert into leads (
      organization_id, first_name, last_name, company_name, company_domain,
      region, source, source_detail, lifecycle_stage, owner_id
    ) values (
      v_org_id, '-', '-', r.company_name, r.domain,
      coalesce(r.region, 'US'), 'Wix Website Inquiry',
      'Migrated from WIX-sourced account (no contact on file)', 'New', r.owner_id
    )
    returning id into v_lead_id;

    insert into account_fallback_lead (account_id, lead_id) values (r.account_id, v_lead_id);

    v_company_leads := v_company_leads + 1;
  end loop;

  -- Re-point interactions that referenced a specific migrated Contact
  update interactions i
  set lead_id = m.lead_id
  from contact_lead_map m
  where i.contact_id = m.contact_id;

  -- Re-point remaining account-level interactions (no contact_id) to that
  -- account's first migrated Lead, so they don't go fully orphaned
  update interactions i
  set lead_id = f.lead_id
  from account_fallback_lead f
  where i.account_id = f.account_id
    and i.contact_id is null
    and i.lead_id is null;

  delete from contacts c using wix_accounts wa where c.account_id = wa.id;
  get diagnostics v_deleted_contacts = row_count;

  delete from accounts a using wix_accounts wa where a.id = wa.id;
  get diagnostics v_deleted_accounts = row_count;

  raise notice 'Created % contact-level leads, % company-level leads. Deleted % contacts, % accounts.',
    v_contact_leads, v_company_leads, v_deleted_contacts, v_deleted_accounts;
end $$;
